#!/usr/bin/env node
/* =========================================================================
   Generates supabase/seed.sql from assets/js/seed.js, so the bundled demo
   catalogue and the database can never drift apart.
   Run:  node qetaa/tools/seed-sql.js
   ========================================================================= */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
global.window = {};
eval(fs.readFileSync(path.join(ROOT, "assets/js/seed.js"), "utf8"));
const SEED = global.window.SEED;

const q = v => v === null || v === undefined || v === "" ? "null" : "'" + String(v).replace(/'/g, "''") + "'";
const n = v => (v === null || v === undefined || v === "" ? "null" : Number(v));
const b = v => (v ? "true" : "false");
const arr = v => "ARRAY[" + (v || []).map(q).join(",") + "]::text[]";

const rows = (table, cols, list, map) =>
  "insert into public." + table + " (" + cols.join(", ") + ") values\n" +
  list.map(r => "  (" + map(r).join(", ") + ")").join(",\n") +
  "\non conflict (id) do nothing;\n";

let sql = `-- =========================================================================
-- QETAA — demo catalogue. Generated by tools/seed-sql.js — do not edit by
-- hand; edit assets/js/seed.js and re-run the generator.
-- Run supabase/schema.sql first.
-- =========================================================================

`;

sql += rows("qetaa_sellers",
  ["id","slug","name","name_en","type","city","district","rating","reviews_count","since","phone","whatsapp","verified","plan","hours","makes","about"],
  SEED.sellers,
  s => [q(s.id), q(s.slug), q(s.name), q(s.name_en), q(s.type), q(s.city), q(s.district),
        n(s.rating), n(s.reviews_count), n(s.since), q(s.phone), q(s.whatsapp),
        b(s.verified), q(s.plan), q(s.hours), arr(s.makes), q(s.about)]);

sql += "\n" + rows("qetaa_listings",
  ["id","ref","part_name","category","make","model","year_from","year_to","condition","origin","price","price_old","qty","oem","seller_id","city","delivery","warranty_days","featured","views","status","notes","created_at"],
  SEED.listings,
  l => [q(l.id), q(l.ref), q(l.part_name), q(l.category), q(l.make), q(l.model),
        n(l.year_from), n(l.year_to), q(l.condition), q(l.origin), n(l.price), n(l.price_old),
        n(l.qty), q(l.oem), q(l.seller_id), q(l.city), arr(l.delivery), n(l.warranty_days),
        b(l.featured), n(l.views), "'published'", q(l.notes), q(l.created_at)]);

sql += "\n" + rows("qetaa_requests",
  ["id","ref","make","model","year","part_name","category","city","urgency","condition_pref","notes","name","status","quotes_count","created_at"],
  SEED.requests,
  r => [q(r.id), q(r.ref), q(r.make), q(r.model), n(r.year), q(r.part_name), q(r.category),
        q(r.city), q(r.urgency), q(r.condition_pref), q(r.notes), q(r.name), q(r.status),
        n(r.quotes_count), q(r.created_at)]);

/* the trigger bumps quotes_count, so seed the quotes with it disabled and
   then restate the counts the seed file declares */
sql += "\nalter table public.qetaa_quotes disable trigger qetaa_quotes_bump;\n\n" +
  rows("qetaa_quotes",
    ["id","request_id","seller_id","price","condition","warranty_days","delivery","note","created_at"],
    SEED.quotes,
    x => [q(x.id), q(x.request_id), q(x.seller_id), n(x.price), q(x.condition),
          n(x.warranty_days), q(x.delivery), q(x.note), q(x.created_at)]) +
  "\nalter table public.qetaa_quotes enable trigger qetaa_quotes_bump;\n";

sql += "\n" + rows("qetaa_reviews",
  ["id","seller_id","name","stars","text","created_at"],
  SEED.reviews,
  v => [q(v.id), q(v.seller_id), q(v.name), n(v.stars), q(v.text), q(v.date)]);

fs.writeFileSync(path.join(ROOT, "supabase/seed.sql"), sql);
console.log("✓ supabase/seed.sql — " + SEED.sellers.length + " sellers, " +
  SEED.listings.length + " listings, " + SEED.requests.length + " requests, " +
  SEED.quotes.length + " quotes, " + SEED.reviews.length + " reviews");
