// ---- EVENT DATA ----------------------------------------------------------
// To add an event: copy one block, change the values, keep the commas.
// The first one is a REAL match (Saudi Pro League, Matchweek 1).
// type: "event" (something happening) or "place" (somewhere to visit).
// image: poster artwork (img/*.svg) shown on the map pin and in the popup.
const EVENTS = [
  {
    id: 1,
    title: "Al-Ettifaq vs Al-Riyadh",
    category: "Football",
    emoji: "⚽",
    venue: "Prince Mohamed bin Fahd Stadium, Dammam",
    time: "Tonight · Aug 14",
    lat: 26.3927,
    lng: 49.9777,
    heat: 90, // 0-100 popularity — drives the glow size
    type: "event",
    image: "img/al-ettifaq-vs-al-riyadh.svg",
    ticketUrl: "https://webook.com"
  },
  {
    id: 2,
    title: "Live Music Night",
    category: "Concert",
    emoji: "🎸",
    venue: "Al Khobar Corniche",
    time: "Tonight · 9:00 PM",
    lat: 26.2870,
    lng: 50.2130,
    heat: 70,
    type: "event",
    image: "img/live-music-night.svg",
    ticketUrl: "https://webook.com"
  },
  {
    id: 3,
    title: "Food & Culture Festival",
    category: "Festival",
    emoji: "🍜",
    venue: "Al Rashid Mall Plaza",
    time: "All weekend",
    lat: 26.3050,
    lng: 50.1980,
    heat: 55,
    type: "event",
    image: "img/food-culture-festival.svg",
    ticketUrl: "https://webook.com"
  },
  {
    id: 4,
    title: "Padel Championship",
    category: "Sports",
    emoji: "🎾",
    venue: "Khobar Sports Hub",
    time: "Tomorrow · 5:00 PM",
    lat: 26.2680,
    lng: 50.2200,
    heat: 40,
    type: "event",
    image: "img/padel-championship.svg",
    ticketUrl: "https://webook.com"
  },
  {
    id: 5,
    title: "Esports Showdown",
    category: "Esports",
    emoji: "🎮",
    venue: "Dhahran Expo",
    time: "Saturday · 7:00 PM",
    lat: 26.3016,
    lng: 50.1477,
    heat: 75,
    type: "event",
    image: "img/esports-showdown.svg",
    ticketUrl: "https://webook.com"
  },
  {
    id: 6,
    title: "Comedy Night",
    category: "Comedy",
    emoji: "🎤",
    venue: "Ajdan Walk, Al Khobar",
    time: "Friday · 9:00 PM",
    lat: 26.2986,
    lng: 50.2211,
    heat: 60,
    type: "event",
    image: "img/comedy-night.svg",
    ticketUrl: "https://webook.com"
  },
  {
    id: 7,
    title: "Heritage Nights",
    category: "Heritage",
    emoji: "🏮",
    venue: "Heritage Village, Dammam",
    time: "Daily · 6–11 PM",
    lat: 26.4344,
    lng: 50.1032,
    heat: 50,
    type: "event",
    image: "img/heritage-nights.svg",
    ticketUrl: "https://webook.com"
  },
  {
    id: 8,
    title: "Open-Air Cinema",
    category: "Cinema",
    emoji: "🎬",
    venue: "Khobar Sea Front",
    time: "Thu–Sat · 8:00 PM",
    lat: 26.2570,
    lng: 50.2090,
    heat: 45,
    type: "event",
    image: "img/open-air-cinema.svg",
    ticketUrl: "https://webook.com"
  },
  {
    id: 9,
    title: "Ithra — King Abdulaziz Center for World Culture",
    category: "Culture",
    emoji: "🏛️",
    venue: "Gharb Al Dhahran, Dhahran",
    time: "Open daily",
    lat: 26.3269,
    lng: 50.1287,
    heat: 65,
    type: "place",
    image: "img/ithra.svg",
    ticketUrl: "https://www.ithra.com/en"
  },
  {
    id: 10,
    title: "Scitech",
    category: "Science",
    emoji: "🔭",
    venue: "Khobar Corniche",
    time: "Open daily",
    lat: 26.2934,
    lng: 50.2145,
    heat: 55,
    type: "place",
    image: "img/scitech.svg",
    ticketUrl: "https://webook.com"
  },
  {
    id: 11,
    title: "Khobar Water Tower",
    category: "Landmark",
    emoji: "🗼",
    venue: "Al Khobar Corniche",
    time: "Best at sunset",
    lat: 26.2907,
    lng: 50.2172,
    heat: 50,
    type: "place",
    image: "img/water-tower.svg",
    ticketUrl: "https://webook.com"
  },
  {
    id: 12,
    title: "Half Moon Bay",
    category: "Beach",
    emoji: "🏖️",
    venue: "Dhahran Coast",
    time: "Open all day",
    lat: 26.1436,
    lng: 50.0339,
    heat: 60,
    type: "place",
    image: "img/half-moon-bay.svg",
    ticketUrl: "https://webook.com"
  },
  {
    id: 13,
    title: "Marjan Island",
    category: "Island",
    emoji: "🏝️",
    venue: "Dammam Corniche",
    time: "Open all day",
    lat: 26.4893,
    lng: 50.1155,
    heat: 45,
    type: "place",
    image: "img/marjan-island.svg",
    ticketUrl: "https://webook.com"
  }
];
