// ---- SEED DATA (fallback) -------------------------------------------------
// A bundled copy of the database contents, used when config.js has no
// Supabase keys or the database is unreachable. Keep it in sync with
// supabase/schema.sql — same 18 rows, already in the app's item shape.
// posterRef: "template:<name>" (see posters.js) or a full image URL.
const SEED_ITEMS = [
  { id: 1,  title: "Al-Ettifaq vs Al-Riyadh", type: "event", category: "Football", emoji: "⚽", venue: "Prince Mohamed bin Fahd Stadium, Dammam", time: "Tonight · Aug 14", start: "2026-08-14", end: "2026-08-14", status: "live", lat: 26.3927, lng: 49.9777, heat: 90, ticketUrl: "https://webook.com", posterRef: "template:football" },
  { id: 2,  title: "Live Music Night", type: "event", category: "Concert", emoji: "🎸", venue: "Al Khobar Corniche", time: "Tonight · 9:00 PM", start: "2026-08-14", end: "2026-08-14", status: "live", lat: 26.2870, lng: 50.2130, heat: 70, ticketUrl: "https://webook.com", posterRef: "template:concert" },
  { id: 3,  title: "Food & Culture Festival", type: "event", category: "Festival", emoji: "🍜", venue: "Al Rashid Mall Plaza", time: "This weekend", start: "2026-08-14", end: "2026-08-15", status: "live", lat: 26.3050, lng: 50.1980, heat: 55, ticketUrl: "https://webook.com", posterRef: "template:candlelight" },
  { id: 4,  title: "Padel Championship", type: "event", category: "Sports", emoji: "🎾", venue: "Khobar Sports Hub", time: "Tomorrow · 5:00 PM", start: "2026-08-15", end: "2026-08-15", status: "soon", lat: 26.2680, lng: 50.2200, heat: 40, ticketUrl: "https://webook.com", posterRef: "template:football" },
  { id: 5,  title: "Esports Showdown", type: "event", category: "Esports", emoji: "🎮", venue: "Dhahran Expo", time: "Saturday · 7:00 PM", start: "2026-08-15", end: "2026-08-15", status: "soon", lat: 26.3016, lng: 50.1477, heat: 75, ticketUrl: "https://webook.com", posterRef: "template:exhibition" },
  { id: 6,  title: "Comedy Night", type: "event", category: "Comedy", emoji: "🎤", venue: "Ajdan Walk, Al Khobar", time: "Fri Aug 21 · 9:00 PM", start: "2026-08-21", end: "2026-08-21", status: "soon", lat: 26.2986, lng: 50.2211, heat: 60, ticketUrl: "https://webook.com", posterRef: "template:exhibition" },
  { id: 7,  title: "Heritage Nights", type: "event", category: "Heritage", emoji: "🏮", venue: "Heritage Village, Dammam", time: "Daily · 6–11 PM", start: "2026-08-14", end: "2026-09-30", status: "live", lat: 26.4344, lng: 50.1032, heat: 50, ticketUrl: "https://webook.com", posterRef: "template:candlelight" },
  { id: 8,  title: "Open-Air Cinema", type: "event", category: "Cinema", emoji: "🎬", venue: "Khobar Sea Front", time: "Thu–Sat · 8:00 PM", start: "2026-08-13", end: "2026-09-26", status: "live", lat: 26.2570, lng: 50.2090, heat: 45, ticketUrl: "https://webook.com", posterRef: "template:exhibition" },
  { id: 9,  title: "Global City Dammam", type: "event", category: "Festival", emoji: "🌍", venue: "Global City, Dammam", time: "Daily · 4 PM–12 AM", start: "2026-08-14", end: "2026-10-31", status: "live", lat: 26.4140, lng: 50.0920, heat: 80, ticketUrl: "https://webook.com/en/zones/global-city-dammam-2026", posterRef: "template:family" },
  { id: 10, title: "The Big Bounce Arabia", type: "event", category: "Family", emoji: "🎈", venue: "Al Khobar", time: "Aug 20–29", start: "2026-08-20", end: "2026-08-29", status: "soon", lat: 26.2790, lng: 50.2060, heat: 65, ticketUrl: "https://webook.com/en/events/the-big-bounce-arabia-alkhobar-25", posterRef: "template:family" },
  { id: 11, title: "Ithra — King Abdulaziz Center for World Culture", type: "place", category: "Culture", emoji: "🏛️", venue: "Gharb Al Dhahran, Dhahran", time: "Open daily", start: null, end: null, status: "open", lat: 26.3354108, lng: 50.1205788, heat: 65, ticketUrl: "https://www.ithra.com/en", posterRef: "template:ithra" },
  { id: 12, title: "Scitech", type: "place", category: "Science", emoji: "🔭", venue: "Khobar Corniche", time: "Open daily", start: null, end: null, status: "open", lat: 26.3191662, lng: 50.227991, heat: 55, ticketUrl: "https://webook.com", posterRef: "template:place" },
  { id: 13, title: "Khobar Water Tower", type: "place", category: "Landmark", emoji: "🗼", venue: "Al Khobar Corniche", time: "Best at sunset", start: null, end: null, status: "open", lat: 26.3077797, lng: 50.2318893, heat: 50, ticketUrl: "https://webook.com", posterRef: "template:watertower" },
  { id: 14, title: "Half Moon Bay", type: "place", category: "Beach", emoji: "🏖️", venue: "Dhahran Coast", time: "Open all day", start: null, end: null, status: "open", lat: 26.1737516, lng: 50.0371724, heat: 60, ticketUrl: "https://webook.com", posterRef: "template:place" },
  { id: 15, title: "Marjan Island", type: "place", category: "Island", emoji: "🏝️", venue: "Dammam Corniche", time: "Open all day", start: null, end: null, status: "open", lat: 26.4835705, lng: 50.1052903, heat: 45, ticketUrl: "https://webook.com", posterRef: "template:place" },
  { id: 16, title: "Dolphin Village", type: "place", category: "Family", emoji: "🐬", venue: "Aziziyah, Al Khobar", time: "Shows daily", start: null, end: null, status: "open", lat: 26.1610, lng: 50.1905, heat: 55, ticketUrl: "https://webook.com", posterRef: "template:place" },
  { id: 17, title: "Tarout Island & Castle", type: "place", category: "Heritage", emoji: "🏰", venue: "Tarout, Qatif", time: "Open all day", start: null, end: null, status: "open", lat: 26.5692578, lng: 50.0660631, heat: 45, ticketUrl: "https://webook.com", posterRef: "template:place" },
  { id: 18, title: "King Fahd Park", type: "place", category: "Park", emoji: "🌳", venue: "North Dammam", time: "Open till late", start: null, end: null, status: "open", lat: 26.3935845, lng: 50.1252057, heat: 50, ticketUrl: "https://webook.com", posterRef: "template:place" }
];
