-- =========================================================================
-- QETAA — demo catalogue. Generated by tools/seed-sql.js — do not edit by
-- hand; edit assets/js/seed.js and re-run the generator.
-- Run supabase/schema.sql first.
-- =========================================================================

insert into public.qetaa_sellers (id, slug, name, name_en, type, city, district, rating, reviews_count, since, phone, whatsapp, verified, plan, hours, makes, about) values
  ('s1', 'al-salay-parts', 'تشليح السلي لقطع الغيار', 'Al-Salay Auto Parts', 'yard', 'riyadh', 'حي السلي — شارع التشاليح', 4.7, 212, 2009, '+966500000001', '966500000001', true, 'pro', 'السبت – الخميس · ٨ص – ١٠م', ARRAY['toyota','lexus','nissan']::text[], 'تشليح متخصص في تويوتا ولكزس منذ ٢٠٠٩. قطع مفحوصة، فاتورة ضريبية، وضمان ١٤ يوم على القطع الميكانيكية.'),
  ('s2', 'shuraia-motors', 'مؤسسة الشرائع لقطع الغيار', 'Shuraia Motors Parts', 'shop', 'khobar', 'شارع الشرائع — الصناعية', 4.5, 148, 2013, '+966500000002', '966500000002', true, 'basic', 'السبت – الخميس · ٩ص – ١١م', ARRAY['chevrolet','gmc','ford']::text[], 'قطع أمريكي وارد ومحلي، تخصص تاهو ويوكن وسلفرادو. شحن لكل مدن المملكة.'),
  ('s3', 'jeddah-japan', 'معرض جدة للوارد الياباني', 'Jeddah Japan Imports', 'shop', 'jeddah', 'الصناعية — طريق المدينة', 4.8, 301, 2007, '+966500000003', '966500000003', true, 'yard', 'يومياً · ٨ص – ١٢م', ARRAY['toyota','honda','mazda','mitsubishi']::text[], 'استيراد مباشر من اليابان: مكاين، قيرات، وقطع داخلية بحالة ممتازة مع تقرير فحص لكل قطعة.'),
  ('s4', 'dammam-korean', 'تشليح الدمام للقطع الكورية', 'Dammam Korean Parts', 'yard', 'dammam', 'الصناعية الثانية', 4.3, 96, 2015, '+966500000004', '966500000004', true, 'basic', 'السبت – الخميس · ٨ص – ٩م', ARRAY['hyundai','kia']::text[], 'كل قطع هيونداي وكيا: صدامات، شمعات، مكاين، وقطع كهرباء مفحوصة.'),
  ('s5', 'german-house', 'البيت الألماني لقطع الغيار', 'German House Parts', 'shop', 'riyadh', 'طريق الخرج — حي الفيصلية', 4.6, 134, 2012, '+966500000005', '966500000005', true, 'pro', 'السبت – الخميس · ٩ص – ١٠م', ARRAY['mercedes','bmw']::text[], 'قطع مرسيدس و BMW وارد أوروبي، مع إمكانية الفحص بجهاز الكمبيوتر قبل البيع.'),
  ('s6', 'qassim-trucks', 'قطع القصيم للوانيتات', 'Qassim Truck Parts', 'yard', 'qassim', 'طريق المدينة — بريدة', 4.2, 64, 2016, '+966500000006', '966500000006', false, 'free', 'السبت – الخميس · ٧ص – ٨م', ARRAY['toyota','isuzu','nissan']::text[], 'تخصص هايلكس ودي ماكس ونافارا: عفشة، مكاين ديزل، وقطع شاصي.'),
  ('s7', 'fast-fit-jubail', 'ورشة الجبيل السريعة', 'Jubail Fast Fit', 'workshop', 'jubail', 'الصناعية — الفناتير', 4.4, 52, 2018, '+966500000007', '966500000007', false, 'free', 'السبت – الخميس · ٨ص – ٨م', ARRAY['hyundai','toyota','kia']::text[], 'ورشة تبيع القطع وتركبها في نفس اليوم، مع ضمان على التركيب.'),
  ('s8', 'abu-mohammed', 'أبو محمد — بيع قطع شخصية', 'Abu Mohammed (individual)', 'person', 'riyadh', 'حي الياسمين', 4.1, 11, 2024, '+966500000008', '966500000008', false, 'free', 'بعد العصر', ARRAY['hyundai']::text[], 'أبيع قطع سيارتي السابقة (سوناتا ٢٠١٧) بعد ما استبدلتها.')
on conflict (id) do nothing;

insert into public.qetaa_listings (id, ref, part_name, category, make, model, year_from, year_to, condition, origin, price, price_old, qty, oem, seller_id, city, delivery, warranty_days, featured, views, status, notes, created_at) values
  ('l1', 'QT-1001', 'صدام أمامي', 'body', 'toyota', 'camry', 2015, 2017, 'b', 'used_sa', 480, 650, 1, '52119-06962', 's1', 'riyadh', ARRAY['pickup','city','shipping']::text[], 7, true, 412, 'published', 'صدام أصلي مفكوك من كامري ٢٠١٦، فيه خدش بسيط من الجهة اليمنى يختفي بالبوليش. الحساسات غير مشمولة.', '2026-09-12'),
  ('l2', 'QT-1002', 'شمعة أمامية يمين', 'lighting', 'toyota', 'landcruiser', 2016, 2020, 'a', 'used_jp', 1450, 0, 2, '81145-60F60', 's3', 'jeddah', ARRAY['pickup','shipping']::text[], 14, true, 588, 'published', 'شمعة LED أصلية وارد ياباني، الزجاج نظيف بدون تشققات، جميع الأرجل سليمة.', '2026-09-14'),
  ('l3', 'QT-1003', 'قير أوتوماتيك', 'gearbox', 'nissan', 'altima', 2013, 2018, 'b', 'used_sa', 2700, 3200, 1, '31020-3TX0C', 's1', 'riyadh', ARRAY['pickup','city']::text[], 14, false, 730, 'published', 'قير CVT مفحوص ومجرب على السيارة قبل الفك، ضمان ١٤ يوم استبدال.', '2026-09-10'),
  ('l4', 'QT-1004', 'كمبيوتر المحرك ECU', 'electric', 'hyundai', 'sonata', 2015, 2019, 'b', 'used_sa', 850, 0, 3, '39131-2GGA5', 's4', 'dammam', ARRAY['pickup','shipping']::text[], 7, false, 265, 'published', 'يحتاج برمجة عند الوكالة أو ورشة كهرباء. نوفر رقم القطعة للتأكد من التطابق.', '2026-09-08'),
  ('l5', 'QT-1005', 'مكينة كاملة', 'engine', 'toyota', 'corolla', 2014, 2019, 'b', 'used_jp', 5200, 6000, 1, '2ZR-FE', 's3', 'jeddah', ARRAY['pickup','shipping','install']::text[], 30, true, 911, 'published', 'مكينة 2ZR وارد ياباني ممشى ٨٠ ألف، مع تقرير فحص ضغط وصور للبساتم.', '2026-09-15'),
  ('l6', 'QT-1006', 'كمبروسر مكيف', 'ac', 'chevrolet', 'tahoe', 2015, 2020, 'b', 'used_us', 690, 0, 2, '84208257', 's2', 'khobar', ARRAY['pickup','city','shipping']::text[], 14, false, 198, 'published', 'مجرب على جهاز الشحن، تبريد ممتاز، مع الكلتش.', '2026-09-11'),
  ('l7', 'QT-1007', 'باب أمامي يسار', 'body', 'hyundai', 'elantra', 2017, 2020, 'c', 'used_sa', 620, 0, 1, '76003-F2000', 's4', 'dammam', ARRAY['pickup','city']::text[], 0, false, 141, 'published', 'باب كامل بالزجاج والماطور، لون فضي، يحتاج دهان جزئي.', '2026-09-06'),
  ('l8', 'QT-1008', 'جنط 20 بوصة (طقم)', 'wheels', 'gmc', 'yukon', 2015, 2020, 'a', 'used_sa', 2400, 2900, 1, null, 's2', 'khobar', ARRAY['pickup','shipping']::text[], 0, false, 377, 'published', 'طقم ٤ جنوط أصلية مقاس ٢٠ بحالة ممتازة، بدون اعوجاج، الإطارات غير مشمولة.', '2026-09-13'),
  ('l9', 'QT-1009', 'مساعد أمامي يمين', 'suspension', 'toyota', 'prado', 2014, 2019, 'b', 'used_sa', 420, 0, 4, '48510-69745', 's1', 'riyadh', ARRAY['pickup','city','shipping']::text[], 7, false, 223, 'published', 'مساعد أصلي بدون تزييت، مجرب.', '2026-09-09'),
  ('l10', 'QT-1010', 'طقم كراسي جلد', 'interior', 'lexus', 'es', 2016, 2021, 'a', 'used_jp', 4800, 5500, 1, null, 's3', 'jeddah', ARRAY['pickup','shipping','install']::text[], 0, true, 642, 'published', 'طقم كامل بيج فاتح، كهرباء وتدفئة تعمل، بدون تشققات.', '2026-09-16'),
  ('l11', 'QT-1011', 'رديتر', 'engine', 'nissan', 'patrol', 2012, 2019, 'b', 'used_sa', 560, 0, 2, '21460-5ZM0A', 's6', 'qassim', ARRAY['pickup','shipping']::text[], 7, false, 167, 'published', 'رديتر أصلي مغسول ومختبر ضغط، بدون تسريب.', '2026-09-07'),
  ('l12', 'QT-1012', 'شمعة خلفية يسار', 'lighting', 'kia', 'cerato', 2019, 2023, 'a', 'used_sa', 380, 0, 1, '92401-M6000', 's4', 'dammam', ARRAY['pickup','city','shipping']::text[], 7, false, 129, 'published', 'شمعة نظيفة بدون كسر في الأرجل، كل اللمبات تعمل.', '2026-09-05'),
  ('l13', 'QT-1013', 'دينمو', 'electric', 'toyota', 'hilux', 2016, 2022, 'b', 'used_sa', 520, 640, 2, '27060-0L090', 's6', 'qassim', ARRAY['pickup','shipping']::text[], 14, false, 203, 'published', 'دينمو مجرب على البنش، شحن ثابت ١٤.٢ فولت.', '2026-09-12'),
  ('l14', 'QT-1014', 'صدام خلفي', 'body', 'mercedes', 'eclass', 2014, 2018, 'b', 'used_eu', 1650, 0, 1, 'A2128850025', 's5', 'riyadh', ARRAY['pickup','shipping']::text[], 0, false, 312, 'published', 'صدام أصلي بحساسات الركن، لون أسود، خدش خفيف أسفل الصدام.', '2026-09-14'),
  ('l15', 'QT-1015', 'طرمبة دركسون', 'suspension', 'ford', 'f150', 2012, 2018, 'c', 'used_us', 340, 0, 1, 'BL3Z-3A674-B', 's2', 'khobar', ARRAY['pickup','shipping']::text[], 7, false, 98, 'published', 'طرمبة تعمل بدون صوت، فيها أثر تسريب خفيف من الجوان تم تنظيفه.', '2026-09-04'),
  ('l16', 'QT-1016', 'شاشة الوسائط', 'interior', 'chevrolet', 'malibu', 2016, 2020, 'b', 'used_us', 760, 900, 1, '84190171', 's2', 'khobar', ARRAY['pickup','shipping']::text[], 14, false, 245, 'published', 'شاشة أصلية تعمل مع أبل كاربلاي، بدون خدوش على اللمس.', '2026-09-10'),
  ('l17', 'QT-1017', 'كبوت', 'body', 'honda', 'accord', 2018, 2022, 'b', 'used_sa', 850, 0, 1, '60100-TVA-A90', 's3', 'jeddah', ARRAY['pickup','shipping']::text[], 0, false, 176, 'published', 'كبوت بدون صدمات، لون أبيض لؤلؤي، جاهز للتركيب.', '2026-09-08'),
  ('l18', 'QT-1018', 'كاليبر فرامل أمامي', 'brakes', 'bmw', 's5', 2013, 2017, 'b', 'used_eu', 720, 0, 2, '34116799465', 's5', 'riyadh', ARRAY['pickup','shipping']::text[], 14, false, 134, 'published', 'كاليبر مع الفحمات، البستم يتحرك بسلاسة.', '2026-09-06'),
  ('l19', 'QT-1019', 'مروحة مكيف (طقم)', 'ac', 'hyundai', 'tucson', 2016, 2020, 'b', 'used_sa', 430, 0, 1, '25380-D3600', 's7', 'jubail', ARRAY['pickup','city','install']::text[], 7, false, 88, 'published', 'طقم مراوح كامل بالغطاء، مجرب ويشتغل على السرعتين.', '2026-09-03'),
  ('l20', 'QT-1020', 'زجاج أمامي', 'glass', 'toyota', 'camry', 2018, 2023, 'a', 'new_after', 640, 0, 5, null, 's1', 'riyadh', ARRAY['pickup','city','install']::text[], 0, false, 159, 'published', 'زجاج جديد تجاري مع فتحة الحساس، التركيب متوفر بـ ١٥٠ ريال.', '2026-09-11'),
  ('l21', 'QT-1021', 'كمبروسر مكيف', 'ac', 'hyundai', 'sonata', 2015, 2019, 'c', 'used_sa', 390, 0, 1, '97701-C1100', 's8', 'riyadh', ARRAY['pickup']::text[], 0, false, 71, 'published', 'مفكوك من سيارتي، يشتغل لكن فيه صوت خفيف عند التشغيل. السعر قابل للتفاوض.', '2026-09-02'),
  ('l22', 'QT-1022', 'عكس (دفرنس) خلفي', 'gearbox', 'toyota', 'landcruiser', 2010, 2015, 'b', 'used_sa', 3100, 3600, 1, '41110-60B00', 's1', 'riyadh', ARRAY['pickup','shipping']::text[], 14, false, 289, 'published', 'عكس كامل بالنسبة الأصلية، بدون أصوات، مجرب على السيارة.', '2026-09-13'),
  ('l23', 'QT-1023', 'مرايا جانبية يمين', 'lighting', 'kia', 'sportage', 2017, 2021, 'a', 'used_sa', 310, 0, 2, '87620-D9', 's4', 'dammam', ARRAY['pickup','city','shipping']::text[], 7, false, 112, 'published', 'مرايا كهرباء بالإشارة والطي، لون أبيض.', '2026-09-09'),
  ('l24', 'QT-1024', 'تربو', 'engine', 'isuzu', 'dmax', 2015, 2020, 'b', 'used_sa', 1850, 0, 1, '8-98178-825-1', 's6', 'qassim', ARRAY['pickup','shipping']::text[], 14, false, 204, 'published', 'تربو نظيف بدون خبط في الريش، محور بدون خلوص.', '2026-09-07'),
  ('l25', 'QT-1025', 'شكمان كامل', 'exhaust', 'chevrolet', 'caprice', 2012, 2017, 'c', 'used_sa', 520, 0, 1, null, 's2', 'khobar', ARRAY['pickup']::text[], 0, false, 93, 'published', 'شكمان كامل مع الكتلايزر، فيه صدأ سطحي.', '2026-09-05'),
  ('l26', 'QT-1026', 'سلف (مارش)', 'electric', 'mitsubishi', 'pajero', 2012, 2019, 'b', 'used_jp', 470, 0, 2, 'MR994325', 's3', 'jeddah', ARRAY['pickup','shipping']::text[], 14, false, 121, 'published', 'سلف وارد ياباني مجرب على البنش.', '2026-09-10'),
  ('l27', 'QT-1027', 'رفرف أمامي يمين', 'body', 'nissan', 'sunny', 2016, 2022, 'b', 'used_sa', 220, 0, 3, '63100-3AW0A', 's4', 'dammam', ARRAY['pickup','city','shipping']::text[], 0, false, 104, 'published', 'رفرف بدون صدأ، يحتاج دهان بلون السيارة.', '2026-09-04'),
  ('l28', 'QT-1028', 'هوب فرامل خلفي', 'brakes', 'toyota', 'hiace', 2014, 2019, 'b', 'used_sa', 280, 0, 4, null, 's7', 'jubail', ARRAY['pickup','city','install']::text[], 7, false, 66, 'published', 'هوب بحالة جيدة مع إمكانية الخراطة والتركيب في الورشة.', '2026-09-01')
on conflict (id) do nothing;

insert into public.qetaa_requests (id, ref, make, model, year, part_name, category, city, urgency, condition_pref, notes, name, status, quotes_count, created_at) values
  ('r1', 'RQ-501', 'toyota', 'camry', 2016, 'صدام أمامي', 'body', 'riyadh', 'week', 'b', 'أبي صدام أمامي أصلي، يفضل لون أبيض ٠٤٠، وإذا فيه حساسات أفضل.', 'سعود', 'open', 3, '2026-09-18'),
  ('r2', 'RQ-502', 'hyundai', 'accent', 2019, 'شمعة أمامية يسار', 'lighting', 'dammam', 'today', 'a', 'السيارة عندي في الفحص الدوري وما تعدي بدون شمعة سليمة.', 'عبدالله', 'open', 2, '2026-09-19'),
  ('r3', 'RQ-503', 'chevrolet', 'tahoe', 2018, 'كمبروسر مكيف', 'ac', 'khobar', 'today', 'b', 'المكيف ما يبرد والورشة قالت الكمبروسر. أبي قطعة مضمونة.', 'فهد', 'open', 1, '2026-09-19'),
  ('r4', 'RQ-504', 'lexus', 'lx', 2013, 'طقم كراسي', 'interior', 'riyadh', 'flex', 'a', 'أبحث عن طقم كراسي بني بحالة ممتازة، ويفضل مع التدفئة.', 'ماجد', 'open', 4, '2026-09-17'),
  ('r5', 'RQ-505', 'kia', 'optima', 2017, 'قير أوتوماتيك', 'gearbox', 'jeddah', 'week', 'b', 'القير يرفس عند التحويل. أبي قير مجرب وبضمان لا يقل عن أسبوعين.', 'وليد', 'open', 2, '2026-09-16'),
  ('r6', 'RQ-506', 'nissan', 'patrol', 2015, 'مساعد خلفي', 'suspension', 'qassim', 'flex', 'b', 'أحتاج مساعدين خلف، والأفضل يكونون طقم.', 'تركي', 'open', 1, '2026-09-15'),
  ('r7', 'RQ-507', 'ford', 'explorer', 2020, 'كمبيوتر المحرك ECU', 'electric', 'riyadh', 'week', 'a', 'أحتاج ECU مطابق للرقم، ويفضل من يوفر خدمة البرمجة.', 'ياسر', 'open', 0, '2026-09-18'),
  ('r8', 'RQ-508', 'mercedes', 'cclass', 2016, 'شمعة أمامية يمين', 'lighting', 'jeddah', 'week', 'b', 'شمعة LED، لو فيها خدش بسيط ما يضر، المهم تشتغل كامل.', 'أحمد', 'open', 2, '2026-09-14')
on conflict (id) do nothing;

alter table public.qetaa_quotes disable trigger qetaa_quotes_bump;

insert into public.qetaa_quotes (id, request_id, seller_id, price, condition, warranty_days, delivery, note, created_at) values
  ('q1', 'r1', 's1', 480, 'b', 7, 'city', 'متوفر عندي صدام أصلي أبيض، جاهز اليوم.', '2026-09-18'),
  ('q2', 'r1', 's4', 520, 'a', 14, 'shipping', 'صدام بحالة ممتازة مع الحساسات، الشحن للرياض يوم واحد.', '2026-09-18'),
  ('q3', 'r1', 's8', 400, 'c', 0, 'pickup', 'صدام فيه خدوش، السعر مغري لو تبي تدهنه.', '2026-09-19'),
  ('q4', 'r2', 's4', 340, 'a', 7, 'city', 'شمعة نظيفة، أقدر أوصلها لك اليوم.', '2026-09-19'),
  ('q5', 'r2', 's7', 390, 'a', 14, 'install', 'مع التركيب في الورشة خلال ساعة.', '2026-09-19'),
  ('q6', 'r3', 's2', 690, 'b', 14, 'city', 'كمبروسر مجرب على جهاز الشحن مع ضمان أسبوعين.', '2026-09-19'),
  ('q7', 'r4', 's3', 4800, 'a', 0, 'shipping', 'طقم بيج متوفر، البني أحاول أوفره خلال أسبوع.', '2026-09-17'),
  ('q8', 'r5', 's3', 3400, 'b', 30, 'shipping', 'قير وارد ياباني مع تقرير فحص وضمان شهر.', '2026-09-16'),
  ('q9', 'r6', 's6', 760, 'b', 7, 'shipping', 'طقم مساعدين خلف أصلي.', '2026-09-15'),
  ('q10', 'r8', 's5', 2100, 'b', 14, 'shipping', 'شمعة LED أصلية وارد أوروبي، مفحوصة بالكمبيوتر.', '2026-09-14')
on conflict (id) do nothing;

alter table public.qetaa_quotes enable trigger qetaa_quotes_bump;

insert into public.qetaa_reviews (id, seller_id, name, stars, text, created_at) values
  ('v1', 's1', 'م. خالد', 5, 'القطعة وصلت نفس اليوم ومطابقة للوصف تماماً. تعامل محترم.', '2026-09-10'),
  ('v2', 's1', 'أبو ريان', 4, 'السعر ممتاز، بس تأخر التوصيل نص يوم عن الموعد.', '2026-09-02'),
  ('v3', 's3', 'سلطان', 5, 'مكينة وارد ياباني نظيفة ومعها تقرير فحص. أنصح فيهم.', '2026-09-12'),
  ('v4', 's2', 'ناصر', 4, 'جنوط اليوكن بحالة ممتازة والشحن للرياض كان سريع.', '2026-09-08'),
  ('v5', 's4', 'هاني', 4, 'قطع كورية متوفرة دائماً، والأسعار منطقية.', '2026-09-05')
on conflict (id) do nothing;
